### ISSUE TITLE
Feature extraction

### ISSUE THREAD

**Issue by mab85** [marcbelmont/dcgan-tensorflow-classifier#1]
@marcbelmont  How to use the discriminator network code of this project to extract feature for images in other dataset or in own dataset?

**Comment by marcbelmont** [comment]
If you want to use a different dataset, you can change https://github.com/marcbelmont/dcgan-tensorflow-classifier/blob/master/main.py#L139
You need to use a numpy array with shape [FLAGS.batch_size, 28, 28, 1]
If you want an image with a different size, update the height and width everywhere in the code..
